name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  PYTHONIOENCODING: "UTF-8"
  MC: "/home/runner/miniconda3"
  PATH: "${{ env.MC }}/bin:/home/runner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:"

jobs:
  tests:
    name: Tests (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.7"]
    steps:
      - name: Install Midadniconda Root
        shell: bash -l {0}
        run: "echo $PATH"
      - uses: actions/checkout@v2
      - name: Set up the Miniconda Root Cache
        uses: actions/cache@v2
        env:
          cache_name: cache-miniconda-root
        with:
          path: ~/miniconda3
          key: ${{ runner.os }}-build-${{ env.cache_name }}
      - name: Install Miniconda Root
        shell: bash -l {0}
        run: "source ./make && make ci_conda_root_env"
      - name: Conda info
        shell: bash -l {0}
        run: conda info
